name: car-background-replacement
channels:
  - defaults
dependencies:
  - python=3.9
  - fastapi
  - uvicorn
  - aiohttp
  - pillow
  - supabase
  - python-dotenv
  - pip:
    - 'httpx[http2]'
    - 'jose'
